.PHONY: all clean src

src:
	cd server; make
	cd lib; make
	cd cli; make

all:
	cd server; make all
	cd lib; make all
	cd cli; make all

clean:
	cd server; make clean
	cd lib; make clean
	cd cli; make clean

